### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by victoriastuart** [statictimes/awesome-static#1]
... front page

broken: 

Which Static Site Generator Should You Choose? Brian Rinaldi; April 2016 

http://www.remotesynthesis.com/general/2016/04/06/which-static-site-generator-should-i-use

works:

http://www.remotesynthesis.com/blog/which-static-site-generator-should-i-use

You can delete this Issue when fixed ;-)

**Comment by geraldb** [comment]
@victoriastuart  Thanks for reporting. Why not fix it yourself ;-) Cheers.
